import 'package:flutter/material.dart';
import '../../../services/api_service.dart';

// --- 1. RECORD MANUAL TRANSACTION (General Income/Expense) ---
class RecordTransactionDialog extends StatefulWidget {
  const RecordTransactionDialog({super.key});

  @override
  State<RecordTransactionDialog> createState() => _RecordTransactionDialogState();
}

class _RecordTransactionDialogState extends State<RecordTransactionDialog> {
  final _formKey = GlobalKey<FormState>();
  final _titleCtrl = TextEditingController();
  final _amountCtrl = TextEditingController();
  final _noteCtrl = TextEditingController();

  String _type = 'expense'; // Default
  bool _isSubmitting = false;

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;
    setState(() => _isSubmitting = true);

    try {
      await ApiService.post('/finance/transactions', {
        "title": _titleCtrl.text.trim(),
        "type": _type,
        "amount": double.parse(_amountCtrl.text.trim()),
        "note": _noteCtrl.text.trim(),
      });
      if (mounted) Navigator.pop(context, true);
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text("Error: $e"), backgroundColor: Colors.red));
        setState(() => _isSubmitting = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: const Text("Record Transaction"),
      content: SizedBox(
        width: 400,
        child: Form(
          key: _formKey,
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              TextFormField(
                controller: _titleCtrl,
                decoration: const InputDecoration(labelText: "Title (e.g. Office Supplies)"),
                validator: (v) => v!.isEmpty ? "Required" : null,
              ),
              const SizedBox(height: 16),
              Row(
                children: [
                  Expanded(
                    child: DropdownButtonFormField<String>(
                      value: _type,
                      decoration: const InputDecoration(labelText: "Type"),
                      items: const [
                        DropdownMenuItem(value: 'expense', child: Text("Expense")),
                        DropdownMenuItem(value: 'income', child: Text("Other Income")),
                      ],
                      onChanged: (v) => setState(() => _type = v!),
                    ),
                  ),
                  const SizedBox(width: 16),
                  Expanded(
                    child: TextFormField(
                      controller: _amountCtrl,
                      decoration: const InputDecoration(labelText: "Amount", prefixText: "ZMW"),
                      keyboardType: const TextInputType.numberWithOptions(decimal: true),
                      validator: (v) => v!.isEmpty ? "Required" : null,
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _noteCtrl,
                decoration: const InputDecoration(labelText: "Note (Optional)"),
                maxLines: 2,
              ),
            ],
          ),
        ),
      ),
      actions: [
        TextButton(onPressed: () => Navigator.pop(context), child: const Text("Cancel")),
        ElevatedButton(
          onPressed: _isSubmitting ? null : _submit,
          child: _isSubmitting ? const SizedBox(width: 16, height: 16, child: CircularProgressIndicator()) : const Text("Save"),
        ),
      ],
    );
  }
}

// --- 2. PAY STUDENT FEES ---
class PayFeesDialog extends StatefulWidget {
  const PayFeesDialog({super.key});

  @override
  State<PayFeesDialog> createState() => _PayFeesDialogState();
}

class _PayFeesDialogState extends State<PayFeesDialog> {
  final _formKey = GlobalKey<FormState>();
  // Renamed for clarity: this now holds the readable Student Code
  final _studentCodeCtrl = TextEditingController();
  final _amountCtrl = TextEditingController();
  bool _isSubmitting = false;

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;
    setState(() => _isSubmitting = true);

    try {
      // NOTE: We no longer use int.parse() because the autogenerated
      // ID is a String (e.g., "STD-001")
      await ApiService.post('/fees/fees/pay', {
        "student_id": _studentCodeCtrl.text.trim(), // Sending the String ID
        "amount": double.parse(_amountCtrl.text.trim()),
      });

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text("Payment processed successfully"), backgroundColor: Colors.green)
        );
        Navigator.pop(context, true);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text("Error: ${e.toString().replaceAll("Exception:", "")}"), backgroundColor: Colors.red)
        );
        setState(() => _isSubmitting = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: const Row(
        children: [
          Icon(Icons.payments_outlined, color: Colors.green),
          SizedBox(width: 10),
          Text("Receive Student Fees"),
        ],
      ),
      content: SizedBox(
        width: 400, // Increased slightly for better look on Web
        child: Form(
          key: _formKey,
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              const Text(
                "Enter the student's registration ID and the amount paid below.",
                style: TextStyle(fontSize: 13, color: Colors.grey),
              ),
              const SizedBox(height: 20),

              // --- STUDENT ID FIELD ---
              TextFormField(
                controller: _studentCodeCtrl,
                decoration: const InputDecoration(
                    labelText: "Student ID",
                    hintText: "e.g. BSC2510001",
                    border: OutlineInputBorder(),
                    prefixIcon: Icon(Icons.badge_outlined)
                ),
                // Changed to text because autogenerated IDs are alphanumeric
                keyboardType: TextInputType.text,
                validator: (v) => v!.isEmpty ? "Student ID is required" : null,
              ),
              const SizedBox(height: 16),

              // --- AMOUNT FIELD ---
              TextFormField(
                controller: _amountCtrl,
                decoration: const InputDecoration(
                    labelText: "Payment Amount",
                    prefixText: "ZMW ",
                    border: OutlineInputBorder(),
                    prefixIcon: Icon(Icons.account_balance_wallet_outlined)
                ),
                keyboardType: const TextInputType.numberWithOptions(decimal: true),
                validator: (v) {
                  if (v == null || v.isEmpty) return "Amount is required";
                  if (double.tryParse(v) == null) return "Enter a valid number";
                  return null;
                },
              ),
            ],
          ),
        ),
      ),
      actions: [
        TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text("Cancel")
        ),
        ElevatedButton(
          onPressed: _isSubmitting ? null : _submit,
          style: ElevatedButton.styleFrom(
              backgroundColor: Colors.green,
              foregroundColor: Colors.white,
              padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12)
          ),
          child: _isSubmitting
              ? const SizedBox(width: 20, height: 20, child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2))
              : const Text("Process Payment"),
        ),
      ],
    );
  }
}