openapi: 3.0.3
info:
  title: Lecturer Portal API
  description: API for Lecturer functionalities including dashboard, schedule, course management, and grading.
  version: 1.0.0

servers:
  - url: https://api.college.edu/v1/lecturer
    description: Production Server

paths:
  # ==========================================
  # DASHBOARD & PROFILE
  # ==========================================
  /profile:
    get:
      summary: Get Lecturer Profile
      description: Returns the lecturer's personal details.
      operationId: lecturerProfileGet
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LecturerProfile"

  /schedule:
    get:
      summary: Get Weekly Schedule
      description: Returns the teaching schedule grouped by day.
      operationId: lecturerScheduleGet
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DailySchedule"

  # ==========================================
  # COURSES
  # ==========================================
  /courses:
    get:
      summary: Get All Assigned Courses
      description: Returns a detailed list of all courses assigned to this lecturer.
      operationId: lecturerCoursesGet
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CourseDetail"

  /courses/summary:
    get:
      summary: Get Courses Summary (Dashboard)
      description: Returns a simplified list of courses for the dashboard widget.
      operationId: lecturerCoursesSummaryGet
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CourseSummary"

  # ==========================================
  # GRADING & STUDENTS
  # ==========================================
  /courses/{course_public_id}/students:
    get:
      summary: Get Enrolled Students for Grading
      description: Returns a list of students enrolled in a specific course.
      operationId: lecturerCourseStudentsGet
      parameters:
        - name: course_public_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
            description: The UUID of the course
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/StudentGradeRecord"

  /courses/{course_public_id}/grades:
    post:
      summary: Submit Grades
      description: Submit grades for a specific course.
      operationId: lecturerGradesPost
      parameters:
        - name: course_public_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GradeSubmission"
      responses:
        "200":
          description: Grades submitted successfully
        "400":
          description: Invalid input

components:
  schemas:
    # --- Profile Models ---
    LecturerProfile:
      type: object
      properties:
        first_name:
          type: string
          example: "Sarah"
        last_name:
          type: string
          example: "Mumba"
        title:
          type: string
          example: "Dr"
        department:
          type: string
          example: "Dept of Computing"
        lecturer_id:
          type: string
          example: "LEC-088"
        avatar_url:
          type: string
          nullable: true

    # --- Schedule Models ---
    DailySchedule:
      type: object
      properties:
        day_name:
          type: string
          enum: [Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday]
          example: "Monday"
        is_research_day:
          type: boolean
          default: false
        classes:
          type: array
          items:
            $ref: "#/components/schemas/ClassSession"

    ClassSession:
      type: object
      properties:
        start_time:
          type: string
          example: "08:00"
        end_time:
          type: string
          example: "10:00"
        course_code:
          type: string
          example: "CS201"
        course_name:
          type: string
          example: "Data Structures"
        location:
          type: string
          example: "Lab 3"
        color_hex:
          type: string
          description: "Hex color code for UI styling"
          example: "#2196F3"

    # --- Course Models ---
    CourseSummary:
      type: object
      description: Simplified course object for dashboard widgets
      properties:
        course_code:
          type: string
          example: "CS201"
        course_name:
          type: string
          example: "Data Structures"
        student_count:
          type: integer
          example: 45

    CourseDetail:
      allOf:
        - $ref: "#/components/schemas/CourseSummary"
        - type: object
          properties:
            semester:
              type: string
              example: "Semester 1, 2024"
            credit_hours:
              type: integer
              example: 4
            description:
              type: string

    # --- Grading Models ---
    StudentGradeRecord:
      type: object
      properties:
        student_public_id:
          type: string
          format: uuid
        student_id:
          type: string
          description: "Human readable ID (e.g. STD-001)"
        first_name:
          type: string
        last_name:
          type: string
        current_score:
          type: number
          nullable: true
          description: "The grade currently assigned (if any)"

    GradeSubmission:
      type: object
      properties:
        status:
          type: string
          enum: [draft, published]
        grades:
          type: array
          items:
            type: object
            properties:
              student_public_id:
                type: string
                format: uuid
              score:
                type: number
