openapi: 3.0.3
info:
  title: Lecturer API
  x-pub-name: lecturer_api
  description: API for Lecturer functionalities including profile, schedule, course management, and grading.
  version: 1.0.0

servers:
  - url: https://api.college.edu/api/v1/lecturer
    description: Production Server

paths:
  /profile:
    get:
      summary: Get Lecturer Profile
      operationId: lecturerProfileGet
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/LecturerProfile"

  /schedule:
    get:
      summary: Get Weekly Schedule
      description: Returns the lecturer's timetable for the currently active semester, grouped by day.
      operationId: lecturerScheduleGet
      tags:
        - Lecturer
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/DailySchedule"

  /courses:
    get:
      summary: Get All Assigned Courses (Current Semester)
      description: Returns a list of courses assigned to the lecturer for the active semester (Odd/Even logic applied).
      operationId: lecturerCoursesGet
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  meta:
                    type: object
                    properties:
                      semester: { type: string, example: "2024-2025 Semester 1" }
                      type: { type: string, example: "Odd (1, 3, 5...)" }
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/CourseAssignment"

  /courses/{course_public_id}:
    get:
      summary: Get Course Details & Student List
      description: Returns detailed course info and the list of students in that specific program cohort.
      operationId: lecturerCourseDetailsGet
      parameters:
        - name: course_public_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CourseCohortDetails"

  /courses/{course_public_id}/grades:
    post:
      summary: Submit or Update Grades
      operationId: lecturerGradesPost
      parameters:
        - name: course_public_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GradeSubmissionBatch"
      responses:
        "200":
          description: Grades submitted successfully
        "400":
          description: Invalid input or validation error

components:
  schemas:
    # ----------------------------------------
    # Profile & Schedule
    # ----------------------------------------
    LecturerProfile:
      type: object
      properties:
        first_name: { type: string }
        last_name: { type: string }
        title: { type: string }
        department: { type: string }
        lecturer_id: { type: string }
        avatar_url: { type: string, nullable: true }

    DailySchedule:
      type: object
      properties:
        day_name:
          type: string
          enum: [ Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday ]
          example: "Monday"
        is_research_day:
          type: boolean
          description: True if there are no classes scheduled for this day.
          example: false
        classes:
          type: array
          items:
            $ref: "#/components/schemas/ClassSession"



    ClassSession:
      type: object
      properties:
        start_time:
          type: string
          description: "Format: HH:mm"
          example: "09:00"
        end_time:
          type: string
          description: "Format: HH:mm"
          example: "11:00"
        course_code:
          type: string
          example: "CS101"
        course_name:
          type: string
          example: "Introduction to Programming"
        location:
          type: string
          description: The room name or building code.
          example: "Lab 2"
        color_hex:
          type: string
          description: A hex color code for UI rendering.
          example: "#4CAF50"

    # ----------------------------------------
    # Course Schemas
    # ----------------------------------------
    CourseAssignment:
      type: object
      properties:
        public_id:
          type: string
          format: uuid
          description: The Course Public ID
        course_name:
          type: string
        course_code:
          type: string
        program_name:
          type: string
          description: The specific program this course belongs to (e.g. BSc Computer Science)
        program_code:
          type: string
        program_public_id:
          type: string
          format: uuid
        semester_sequence:
          type: integer
          example: 1
          description: The curriculum sequence (1 = Sem 1 Year 1, 3 = Sem 1 Year 2, etc.)

    CourseCohortDetails:
      type: object
      properties:
        course:
          type: object
          properties:
            name: { type: string }
            code: { type: string }
            description: { type: string, nullable: true }
        program:
          type: object
          properties:
            name: { type: string }
            code: { type: string }
        context:
          type: object
          properties:
            semester_sequence: { type: integer }
            student_count: { type: integer }
        students:
          type: array
          items:
            $ref: "#/components/schemas/StudentGradeRecord"

    # ----------------------------------------
    # Student & Grading Schemas
    # ----------------------------------------
    StudentGradeRecord:
      type: object
      properties:
        public_id:
          type: string
          format: uuid
        student_id:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        avatar:
          type: string
          nullable: true
        current_grade:
          type: number
          format: float
          nullable: true
          description: The existing grade if already submitted
        current_status:
          type: string
          enum: [ PASS, FAIL, PENDING ]
          nullable: true

    GradeSubmission:
      type: object
      required: [ student_public_id, total_score ]
      properties:
        student_public_id:
          type: string
          format: uuid
        total_score:
          type: number
          format: float
          minimum: 0
          maximum: 100
        remarks:
          type: string
          nullable: true

      # 2. The Batch Wrapper
    GradeSubmissionBatch:
      type: object
      required: [ students ]
      properties:
        students:
          type: array
          items:
            $ref: "#/components/schemas/GradeSubmission"